### ISSUE TITLE
Intermittant Error: write after end

### ISSUE THREAD

**Issue by BurtHarris** [BurtHarris/gulp-first#1]
Sometimes using this with gulp I get:

```
C:\code\antlr4ts\node_modules\kew\kew.js:198
      throw e
      ^

Error: write after end
    at writeAfterEnd (C:\code\antlr4ts\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:276:12)
    at DestroyableTransform.Writable.write (C:\code\antlr4ts\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:320:20)
    at Newer.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Newer.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Newer.Readable.push (_stream_readable.js:197:10)
    at Newer.Transform.push (_stream_transform.js:151:32)
    at C:\code\antlr4ts\node_modules\gulp-newer\index.js:198:18
```

**Comment by BurtHarris** [comment]
This issue has been more persistant than I expected.   Working on a fix now.
